---
title: "MU_Zadaca3"
author: "Ema Rudalija"
date: "1/15/2022"
output: html_document
---

Studenti: Amina Alagić (1966/18425), Nejra Rovčanin (1960/18480), Ema Rudalija (1974/18555)

Nastavna grupa: Grupa 2

# Zadaca 3

## Zadatak1

## a)

##učitavanje dataseta i smanjenje broja redova radi lakseg procesiranja

```{r}
podaci <- read.csv("bankmarketing.csv", fileEncoding = 'UTF-8')

#podaci <- podaci[-c(2501:41188),]


```

## tipovi podataka i njihova distribucija
```{r}
boxplot(podaci$age)
boxplot(podaci$duration)
boxplot(podaci$campaign)
boxplot(podaci$pdays)
boxplot(podaci$previous)
boxplot(podaci$emp.var.rate)
boxplot(podaci$cons.price.idx)
boxplot(podaci$cons.conf.idx)
boxplot(podaci$euribor3m)
boxplot(podaci$nr.employed)
```
```{r}

barplot(table(podaci$job))
barplot(table(podaci$marital))
barplot(table(podaci$education))
barplot(table(podaci$default))
barplot(table(podaci$housing))
barplot(table(podaci$loan))
barplot(table(podaci$contact))
barplot(table(podaci$month))
barplot(table(podaci$day_of_week))
barplot(table(podaci$poutcome))
```

##transformacija atributa
```{r}
podaci$job <- as.numeric(factor(podaci$job))
podaci$marital <- as.numeric(factor(podaci$marital))
podaci$education <- as.numeric(factor(podaci$education))
podaci$default <- as.numeric(factor(podaci$default))
podaci$housing <- as.numeric(factor(podaci$housing))
podaci$loan <- as.numeric(factor(podaci$loan))
podaci$contact <- as.numeric(factor(podaci$contact))
podaci$month <- as.numeric(factor(podaci$month))
podaci$day_of_week <- as.numeric(factor(podaci$day_of_week))
podaci$poutcome <- as.numeric(factor(podaci$poutcome))


rows <- sample(nrow(podaci))
podaci <- podaci[rows, ]
end <- length(podaci$job)
n <- as.integer(0.8 * end)
podaci_train <- podaci[1 : n, ]
podaci_test <- podaci[(n + 1) : end, ]

podaci <- podaci_test

```

## klastering tendencija
```{r}
library(clustertend) 
library(factoextra)
distance <- get_dist(podaci, method = "manhattan") 
fviz_dist(distance, gradient = list(low = "blue", mid = "white", high = "red")) 
distance <- get_dist(podaci, method = "euclidean") 
fviz_dist(distance, gradient = list(low = "blue", mid = "white", high = "red")) 
distance <- get_dist(podaci, method = "minkowski") 
fviz_dist(distance, gradient = list(low = "blue", mid = "white", high = "red")) 
distance <- get_dist(podaci, method = "pearson") 
fviz_dist(distance, gradient = list(low = "blue", mid = "white", high = "red"))

```

##b) i c)
```{r}
library(cluster)
library(factoextra)

podaci <- subset(podaci, select = -c(y))
podaci = subset(podaci, podaci$duration < 500 & podaci$campaign < 4)
 
podaci <- na.omit(podaci)

fviz_nbclust(podaci, kmeans, method = "wss")
fviz_nbclust(podaci, kmeans, method = "silhouette")

model <- kmeans(podaci, centers = 2)
plot(podaci[c("duration", "cons.price.idx")], col = model$cluster)
plot(podaci[c("euribor3m", "duration")], col = model$cluster)

model <- pam(podaci, k = 2)
plot(podaci[c("duration", "cons.price.idx")], col = model$cluster)
plot(podaci[c("euribor3m", "duration")], col = model$cluster)

```
##dodatna preprocesiranja 

```{r}
library(stats)

podaci <- subset(podaci, select = -c(nr.employed))
podaci <- subset(podaci, select = -c(month))
podaci <- subset(podaci, select = -c(previous))
podaci <- subset(podaci, select = -c(poutcome))
podaci <- subset(podaci, select = -c(contact))
podaci <- subset(podaci, select = -c(emp.var.rate))
podaci <- subset(podaci, select = -c(pdays))
podaci <- subset(podaci, select = -c(cons.price.idx))
podaci <- subset(podaci, select = -c(cons.conf.idx))
podaci <- subset(podaci, select = -c(y))

pca <- prcomp(podaci, scale. = TRUE)

library(factoextra)
fviz_eig(pca)
summary(pca)

fviz_pca_var(pca,
 col.var = "contrib",
 gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
 repel = TRUE
 )

```

## d)

```{r}
newdata <- predict(pca, podaci)
newdata <- newdata[, 1:8]
newdata <- data.frame(newdata)


```

```{r}
model <- kmeans(newdata, centers = 2)
plot(newdata[c("PC1", "PC2")], col = model$cluster)
plot(newdata[c("PC2", "PC4")], col = model$cluster)
fviz_cluster(model, data = newdata)
model <- pam(newdata, k = 2)
plot(newdata[c("PC1", "PC2")], col = model$cluster)
plot(newdata[c("PC2", "PC4")], col = model$cluster)
fviz_cluster(model, data = newdata)

```